### ISSUE TITLE
unable to create a company as a completely new user on testing

### ISSUE THREAD

**Issue by alisoniven** [sharewave/frontus#1346]
not sure what is wrong here.... 

![screen shot 2015-01-12 at 12 07 58 pm](https://cloud.githubusercontent.com/assets/6333864/5707060/b1e21f1e-9a53-11e4-94ad-b1fa861ff987.png)

**Comment by elizabethkilson** [comment]
@BertHartm I'm guessing this is you?
     [java] [/var/repo/backus/scripts/stripeCLI.py, create_customer, tok_15KBf62WxwQwXozsbuhXuQZ2, 001-14daytrial, , alison+startup@sharewave.com]
     [java] Jan 12, 2015 5:06:21 PM com.sharewave.SWBrijj procPrivate
     [java] SEVERE: org.postgresql.util.PSQLException: ERROR: insert or update on table "user_table" violates foreign key constraint "primary_email_user_fk"
     [java]   Detail: Key (email, primary_email)=(alison+startup@sharewave.com, alison+startup@sharewave.com) is not present in table "user_emails".
     [java]   Where: SQL statement "INSERT INTO account.user_table (email, name, password, primary_email)
     [java]             VALUES (pemail, pname, ppass, pemail)"
     [java] PL/pgSQL function account.one_step_register(account.email,character varying,character varying,character varying,character varying,character varying,character varying,character varying) line 6 at SQL statement

**Comment by alisoniven** [comment]
this was me.

On Mon, Jan 12, 2015 at 12:53 PM, Elizabeth Kilson <notifications@github.com
> wrote:

> @BertHartm <https://github.com/BertHartm> I'm guessing this is you?
> [java] [/var/repo/backus/scripts/stripeCLI.py, create_customer,
> tok_15KBf62WxwQwXozsbuhXuQZ2, 001-14daytrial, ,
> alison+startup@sharewave.com]
> [java] Jan 12, 2015 5:06:21 PM com.sharewave.SWBrijj procPrivate
> [java] SEVERE: org.postgresql.util.PSQLException: ERROR: insert or update
> on table "user_table" violates foreign key constraint
> "primary_email_user_fk"
> [java] Detail: Key (email, primary_email)=(alison+startup@sharewave.com,
> alison+startup@sharewave.com) is not present in table "user_emails".
> [java] Where: SQL statement "INSERT INTO account.user_table (email, name,
> password, primary_email)
> [java] VALUES (pemail, pname, ppass, pemail)"
> [java] PL/pgSQL function account.one_step_register(account.email,character
> varying,character varying,character varying,character varying,character
> varying,character varying,character varying) line 6 at SQL statement
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharewave/frontus/issues/1346#issuecomment-69612871>.
>



-- 
alison iven   |   designer   |   917-743-0016   |   alisoniven.com
<http://alisoniven.com/>
<http://pie-wich.com/>

**Comment by BertHartm** [comment]
Should be fixed.
