### ISSUE TITLE
If I start entering a number, the total the bottom doesn't respond correctly. 

### ISSUE THREAD

**Issue by alisoniven** [sharewave/frontus#1375]
If I start entering a number, the total the bottom doesn't respond correctly until I click off. When I click off, the total is correct again... 
![screen shot 2015-01-15 at 11 45 50 am](https://cloud.githubusercontent.com/assets/6333864/5761847/260a3a2a-9cac-11e4-8857-1d68f556e267.png)

**Comment by BertHartm** [comment]
It won't until the transaction is saved. It'd be hard to change this as the
user can enter gibberish, and there are a lot of values that would need to
change.

Also, irrelevant in the new designs, no?

**Comment by alisoniven** [comment]
Fair enough.

On Thu, Jan 15, 2015 at 11:57 AM, Bert Hartmann <notifications@github.com>
wrote:

> It won't until the transaction is saved. It'd be hard to change this as
> the
> user can enter gibberish, and there are a lot of values that would need to
> change.
>
> Also, irrelevant in the new designs, no?
>
> On Thu, Jan 15, 2015 at 11:46 AM, alisoniven <notifications@github.com>
> wrote:
>
> > If I start entering a number, the total the bottom doesn't respond
> > correctly.
> > [image: screen shot 2015-01-15 at 11 45 50 am]
> > <
> https://cloud.githubusercontent.com/assets/6333864/5761847/260a3a2a-9cac-11e4-8857-1d68f556e267.png>
>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/sharewave/frontus/issues/1375>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharewave/frontus/issues/1375#issuecomment-70118861>.
>



-- 
alison iven   |   designer   |   917-743-0016   |   alisoniven.com
<http://alisoniven.com/>
<http://pie-wich.com/>
