### ISSUE TITLE
Update Add contacts who aren't on cap table to share with modal

### ISSUE THREAD

**Issue by alisoniven** [sharewave/frontus#1398]
see comp at edits > edits-2015.01.21B.ai
current modal looks pretty unfinished and should look like the one below
![screen shot 2015-01-21 at 11 12 40 am](https://cloud.githubusercontent.com/assets/6333864/5839777/837ecc6e-a15e-11e4-95de-81c80cfb4f05.png)

**Comment by BertHartm** [comment]
the grey background will have to be a different ticket, as that's more than
a change to this modal.

**Comment by alisoniven** [comment]
fiiiiine


On Wed, Jan 21, 2015 at 11:23 AM, Bert Hartmann <notifications@github.com>
wrote:

> the grey background will have to be a different ticket, as that's more
> than
> a change to this modal.
>
> On Wed, Jan 21, 2015 at 11:14 AM, alisoniven <notifications@github.com>
> wrote:
>
> > see comp at edits > edits-2015.01.21B.ai
> > current modal looks pretty unfinished and should look like the one below
> > [image: screen shot 2015-01-21 at 11 12 40 am]
> > <
> https://cloud.githubusercontent.com/assets/6333864/5839777/837ecc6e-a15e-11e4-95de-81c80cfb4f05.png>
>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/sharewave/frontus/issues/1398>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharewave/frontus/issues/1398#issuecomment-70868149>.
>



-- 
alison iven   |   designer   |   917-743-0016   |   alisoniven.com
<http://alisoniven.com/>
<http://pie-wich.com/>
