### ISSUE TITLE
when i click "bulk prepare" i'm not sure what to do. all previous options disappeared

### ISSUE THREAD

**Issue by alisoniven** [sharewave/frontus#1410]
default landing
![screen shot 2015-01-21 at 11 59 53 am](https://cloud.githubusercontent.com/assets/6333864/5840649/18ae8aa8-a165-11e4-8fed-6faedb38147d.png)

clicked bulk prepare:
looks like the grid disappeared here....
![screen shot 2015-01-21 at 11 59 57 am](https://cloud.githubusercontent.com/assets/6333864/5840652/1ea704b2-a165-11e4-9e3f-d6109dc37d8e.png)

**Comment by BertHartm** [comment]
Dupe #1070
