### ISSUE TITLE
Only show cap table permissions on members who have been shared the cap table.

### ISSUE THREAD

**Issue by alisoniven** [sharewave/frontus#1415]
Only show cap table permissions on members who have been shared the cap table. Other roles should not have this option.
![sharewave home](https://cloud.githubusercontent.com/assets/6333864/5841126/78079b90-a168-11e4-84e9-00a2ae6dbc32.png)

**Comment by RWalport** [comment]
This is no longer true. We're smart about whether you're on the cap table so can allow people to permission from here if they so choose.
