### ISSUE TITLE
Entering my birthday within an annotation jumbles the date

### ISSUE THREAD

**Issue by alisoniven** [sharewave/frontus#1418]
weird date format (not what issuer choose)
![screen shot 2015-01-21 at 12 30 57 pm](https://cloud.githubusercontent.com/assets/6333864/5841239/720d3d2a-a169-11e4-9623-aebf36533f76.png)

when I rollover though, it's ok
![screen shot 2015-01-21 at 12 31 01 pm](https://cloud.githubusercontent.com/assets/6333864/5841243/76f1ad76-a169-11e4-981b-0d447433d5b9.png)

**Comment by r0ml** [comment]
Would be fixed by #1506
