### ISSUE TITLE
First experience making a group. Group dropdown to be just a button to activate the modal.

### ISSUE THREAD

**Issue by alisoniven** [sharewave/frontus#1426]
First experience making a group.
Group dropdown to be just a button to activate the modal. (peeps and docs)
Once user has created a group, the dropdown like now is purrrrfect.

![screen shot 2015-01-21 at 2 31 37 pm](https://cloud.githubusercontent.com/assets/6333864/5843392/5b156ac8-a17a-11e4-88d8-001f11ff475e.png)

![giphy](https://cloud.githubusercontent.com/assets/6333864/5843413/6dea4c04-a17a-11e4-9d5f-e22801c7cde6.gif)

**Comment by RWalport** [comment]
Done. Good call
