### ISSUE TITLE
confused where my plan is upgraded by looking at contact library.

### ISSUE THREAD

**Issue by alisoniven** [sharewave/frontus#1430]
Are you want to call them members? As I look at my contact library, I know my plan goes up after x amount of shareholders, but it's not reflected here. Since the rail is counting my contacts, can we tag them as shareholders or add another category? 

![sharewave home](https://cloud.githubusercontent.com/assets/6333864/5843858/a1a0b6e8-a17d-11e4-8f38-df642065f16a.png)

**Comment by BertHartm** [comment]
Equity shareholders are counted differently than members.
e.g.
A company with 10 rows, all associated with the same contact, would see 1
person on the people page, but still count as 10 towards the equity
shareholder limit.
In the other direction, a company with 10 convertible debt holders, each
associated with a different contact would see 10 people on this page, but
none would count towards the equity shareholders.

This page is probably won't be able to show or explain the plan limits
easily.

**Comment by RWalport** [comment]
Removed members as unhelpful in every way.
