### ISSUE TITLE
Doc group Permissions should have check box. 

### ISSUE THREAD

**Issue by alisoniven** [sharewave/frontus#1438]
Permissions should have check box. instead of long weird thing
![screen shot 2015-01-21 at 3 43 51 pm](https://cloud.githubusercontent.com/assets/6333864/5844750/594a3188-a184-11e4-97bf-d7ffcbd19dfd.png)

**Comment by elizabethkilson** [comment]
Note: this breakage was probably related to to a similar problem on the plan selector (in cmn/partials)
![screenshot](https://cloud.githubusercontent.com/assets/6598576/5881394/94b8b312-a30e-11e4-9c7a-9bab3cb5e1d2.png)
