### ISSUE TITLE
filters are a bit confusing with the "contact" filter.

### ISSUE THREAD

**Issue by alisoniven** [sharewave/frontus#1440]
i only have one contact. I don't think that my owner account should be duplicated in the "contact" filter.

The "contact" filter feels weird as a term. Isn't the whole feature called "contact". This filter should be more descriptive as to what it actually means...

![sharewave home](https://cloud.githubusercontent.com/assets/6333864/5845295/e791f36e-a188-11e4-831e-4c0aa567304b.png)

**Comment by RWalport** [comment]
Removed. Not actually useful as it's the same as pressing all contacts
