### ISSUE TITLE
Changing a contact from a member to an admin doesn't change their view.

### ISSUE THREAD

**Issue by alisoniven** [sharewave/frontus#1447]
Changing a contact from a member to an admin doesn't change their view.

Changed New Guy 1 to an admin:
![screen shot 2015-01-22 at 11 12 09 am](https://cloud.githubusercontent.com/assets/6333864/5859351/ac0533ac-a227-11e4-9df2-63109a2733ca.png)

According to Help, they should be able to see most everything:
![screen shot 2015-01-22 at 11 12 47 am](https://cloud.githubusercontent.com/assets/6333864/5859356/b58ee97c-a227-11e4-92f7-3469f7548a7c.png)

But when New Guy 1 logs in, the view doesn't show anything more than the cap table share from earlier:
![screen shot 2015-01-22 at 11 14 10 am](https://cloud.githubusercontent.com/assets/6333864/5859374/cb9f2254-a227-11e4-9d82-ddd26757b759.png)

**Comment by elizabethkilson** [comment]
Cannot reproduce. Did you check the companies tab for New Guy 1? He could have been set to be both administrator and investor, so he would have to click the companies tab and pick administrator on that company.

**Comment by alisoniven** [comment]
yeah, my bad.
