### ISSUE TITLE
Auditor doesn't have access to documents

### ISSUE THREAD

**Issue by alisoniven** [sharewave/frontus#1449]
Auditor doesn't have access to documents, which it should according to help.
![screen shot 2015-01-22 at 11 22 28 am](https://cloud.githubusercontent.com/assets/6333864/5859536/fa20eb34-a228-11e4-9b15-7932ab664782.png)

Auditor view:
![screen shot 2015-01-22 at 11 21 55 am](https://cloud.githubusercontent.com/assets/6333864/5859525/ebc921b4-a228-11e4-9f4f-27aeccb1a74c.png)

Owner view:
![screen shot 2015-01-22 at 11 21 59 am](https://cloud.githubusercontent.com/assets/6333864/5859527/f196a7ce-a228-11e4-9563-728a6fcc9160.png)

**Comment by RWalport** [comment]
That's a typo in the docs. They only get cap table associated documents (which these aren't). I have updated the faqs.
