### ISSUE TITLE
Not sure why sometimes a member/contact has all three radio buttons and sometimes only two.

### ISSUE THREAD

**Issue by alisoniven** [sharewave/frontus#1457]
Not sure why sometimes a member/contact has all three radio buttons and sometimes only two. If member has been shared cap, all three buttons to appear.

![screen shot 2015-01-22 at 2 23 00 pm](https://cloud.githubusercontent.com/assets/6333864/5862748/374b3c62-a242-11e4-8b60-b9fe320318d7.png)

**Comment by elizabethkilson** [comment]
Personal view can't be an option unless they are attached to a row. Are you saying the bug is that they sometimes don't get that option when they do have a captable row?

**Comment by alisoniven** [comment]
yeah. you're right (stop being right!) 
once we have the tab to indicate they have ownership, i'll be less confused. currently, i don't know if they are on the cap or not.
