### ISSUE TITLE
No red text on edit profile modal.

### ISSUE THREAD

**Issue by alisoniven** [sharewave/frontus#1458]
No red text on edit profile modal. (yucks)
![screen shot 2015-01-22 at 2 24 09 pm](https://cloud.githubusercontent.com/assets/6333864/5862764/5cd3b6f8-a242-11e4-9223-931dab37f45f.png)

**Comment by alisoniven** [comment]
ps. i've decided innappropriate use of red is a bug ;)

**Comment by seanmcintyre** [comment]
Think of it like special under construction paint.
