### ISSUE TITLE
Any way to remove placeholder scroll bar in rail on profile?

### ISSUE THREAD

**Issue by alisoniven** [sharewave/frontus#1461]
![sharewave home](https://cloud.githubusercontent.com/assets/6333864/5862882/92c4c602-a243-11e4-9a19-b7c0b88b66fb.png)

**Comment by seanmcintyre** [comment]
If OS X detects external mice/keyboards/drawing pads/etc it automatically adds scrollbars.  In theory, it might be possible to work around, but it's probably somewhat we should look into later.
