### ISSUE TITLE
"+ add address" in modal not doing anything

### ISSUE THREAD

**Issue by alisoniven** [sharewave/frontus#1463]
"+ add address" in modal not doing anything
![sharewave home](https://cloud.githubusercontent.com/assets/6333864/5862925/dde104f2-a243-11e4-9a66-6d92a431691e.png)

**Comment by seanmcintyre** [comment]
I can't replicate this.  It might already be fixed.  Can you show me a page this is happening on?

**Comment by alisoniven** [comment]
this was before you released sorry
