### ISSUE TITLE
If I click on my own profile, I should go straight to edit mode

### ISSUE THREAD

**Issue by alisoniven** [sharewave/frontus#1468]
If I click on my own profile, I should go straight to edit mode

my profile:
![screen shot 2015-01-22 at 2 51 02 pm](https://cloud.githubusercontent.com/assets/6333864/5863270/45c0ebc6-a246-11e4-9be2-c5c0b3d67a62.png)

What I see currently:
![screen shot 2015-01-22 at 2 51 07 pm](https://cloud.githubusercontent.com/assets/6333864/5863272/49cece9a-a246-11e4-9790-b9ae01303f71.png)

What I should see"
![2014 09-people5](https://cloud.githubusercontent.com/assets/6333864/5863281/60026410-a246-11e4-9868-e2537ade16aa.png)

**Comment by BertHartm** [comment]
I think we're still using the /app/account/profile page for this for now.
Should redirect the user to that when they look at their own profile.

**Comment by seanmcintyre** [comment]
I believe @RWalport (and @BertHartm ?) and I talked about the edit button sending users to /app/account/profile rather than an automatic redirect.

@RWalport ?

**Comment by RWalport** [comment]
We've now talked about this but we're going to a partial switch we the other account page going away and this one allowing you to manage all your stuff
