### ISSUE TITLE
Created a custom type for my address. But upon refresh, it didn't remember

### ISSUE THREAD

**Issue by alisoniven** [sharewave/frontus#1472]
Created a custom type for my address. But upon refresh, it didn't remember

What I created:
![screen shot 2015-01-22 at 3 25 55 pm](https://cloud.githubusercontent.com/assets/6333864/5863894/0d4c4c7c-a24b-11e4-82ae-4a9e5563e578.png)
 
after a refresh:
![screen shot 2015-01-22 at 3 26 08 pm](https://cloud.githubusercontent.com/assets/6333864/5863899/12d169a2-a24b-11e4-9456-d37be961d25f.png)

**Comment by seanmcintyre** [comment]
Did you click "Save Changes"?

**Comment by alisoniven** [comment]
yup

On Thu, Jan 22, 2015 at 3:30 PM, Sean <notifications@github.com> wrote:

> Did you click "Save Changes"?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharewave/frontus/issues/1472#issuecomment-71092788>.
>



-- 
alison iven   |   designer   |   917-743-0016   |   alisoniven.com
<http://alisoniven.com/>
<http://pie-wich.com/>
