### ISSUE TITLE
unable to edit my personal shareholder account

### ISSUE THREAD

**Issue by alisoniven** [sharewave/frontus#1475]
unable to edit my personal shareholder account. Add edit button to activate modal if we aren't ready to move to new design
![screen shot 2015-01-22 at 3 33 57 pm](https://cloud.githubusercontent.com/assets/6333864/5864001/1efefb62-a24c-11e4-919e-75dbe4f913ec.png)

the addresses also look crummy
move right 40px (to align with everything) and stack like when owner views the profile.

**Comment by RWalport** [comment]
This page is being eliminated.
