### ISSUE TITLE
decrease number of scroll bars on rail in profile.

### ISSUE THREAD

**Issue by alisoniven** [sharewave/frontus#1476]
decrease number of scroll bars on rail in profile. (none are particularly relevant)
![screen-shot-2015-01-22-at-3 39 27-pm](https://cloud.githubusercontent.com/assets/6333864/5864095/ffa998a2-a24c-11e4-988e-514a2ebfb263.png)

**Comment by BertHartm** [comment]
that extra scrollbar may not just be a safari / osx thing either.

this is FF / ubuntu
![image](https://cloud.githubusercontent.com/assets/508811/5864524/a23ccf32-a250-11e4-8730-a38e7db52833.png)
