### ISSUE TITLE
how come "+address" and "+telephone" only appear after i've entered things?

### ISSUE THREAD

**Issue by alisoniven** [sharewave/frontus#1491]
how come "+address" and "+telephone" only appear after i've entered things?

before:
![screen shot 2015-01-23 at 11 12 32 am](https://cloud.githubusercontent.com/assets/6333864/5877880/cd2bdb34-a2f0-11e4-9f1a-91a630813775.png)

after:
![screen shot 2015-01-23 at 11 12 43 am](https://cloud.githubusercontent.com/assets/6333864/5877882/d2452c60-a2f0-11e4-822c-0e0394ede8f9.png)

**Comment by seanmcintyre** [comment]
We don't want people to add another one if they last one is blank.  Do you think it should work differently?
