### ISSUE TITLE
try to keep role descriptions 1-2 lines

### ISSUE THREAD

**Issue by alisoniven** [sharewave/frontus#1492]
![sharewave home](https://cloud.githubusercontent.com/assets/6333864/5879452/70118ed2-a2fd-11e4-9f27-0b421ddc35e7.png)

**Comment by RWalport** [comment]
We're going to make this a tooltip as we want all the text to be there.

**Comment by alisoniven** [comment]
too much text for a tool tip. just make line length longer. there's a lot
of extra space to the right of the text.

On Fri, Jan 23, 2015 at 2:53 PM, RWalport <notifications@github.com> wrote:

> We're going to make this a tooltip as we want all the text to be there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharewave/frontus/issues/1492#issuecomment-71254582>.
>



-- 
alison iven   |   designer   |   917-743-0016   |   alisoniven.com
<http://alisoniven.com/>
<http://pie-wich.com/>

**Comment by RWalport** [comment]
Ok. Let's go with the "learn more about roles" link to the faq page: http://docs.sharewave.com/article/59-roles
