### ISSUE TITLE
As a zombie, I shouldn't be able to do anything but view what has been entered previously.

### ISSUE THREAD

**Issue by alisoniven** [sharewave/frontus#1493]
As a zombie, I shouldn't be able to do anything but view what has been entered previously.
--- role; group; share cap via role change to contact, edit profile

first view
![screen shot 2015-01-23 at 12 46 08 pm](https://cloud.githubusercontent.com/assets/6333864/5879502/ea724bbc-a2fd-11e4-9013-a7836ef3e158.png)
changin stuff
![screen shot 2015-01-23 at 12 46 28 pm](https://cloud.githubusercontent.com/assets/6333864/5879505/eb667e80-a2fd-11e4-946a-a3b9ffdc1f2e.png)

* another weird thing that happened. was that when i first viewed contact library, only three owner accounts were visible and once i changed some stuff a lot of random accounts not previously there appeared... no screengrab, sorry, wasn't expecting...

**Comment by jslevine** [comment]
people should be able to access zombied companies. for example, if you were an employee of a zombie company you might have options in that company and still have a vesting shares/options. YOU MIGHT NEED TO BE ABLE TO UPDATE YOUR EMAIL ADDRESS, MAILING ADDRESS, i.e. your PEOPLE PROFILE.
