### ISSUE TITLE
clicking on contact group name in library doesn't sort

### ISSUE THREAD

**Issue by alisoniven** [sharewave/frontus#1510]
clicking on contact group name in library doesn't sort
![screen shot 2015-01-26 at 1 33 57 pm](https://cloud.githubusercontent.com/assets/6333864/5905693/0624887a-a560-11e4-8c42-1b58ba5f0bc1.png)

**Comment by RWalport** [comment]
This now works. I've also converted over the people section to exactly mimic the documents. The filters work identically (including session storage) and you now get the text at the top that tells you how many have been filtered.
