### ISSUE TITLE
Profile Telephone info

### ISSUE THREAD

**Issue by alisoniven** [sharewave/frontus#1516]
- [x] make telephone have a defualt type on edit profile modal
- [x] remove telephone place holder on profile if not entered.
- [x] remove "e." and "t." from profile and create title above telephone ( like addresses)
should be:

email address
alison@sharewave.com

work telephone
987-837-3847

![47f05ecc-a561-11e4-93d3-46415a3e39e1](https://cloud.githubusercontent.com/assets/6333864/5921022/d26b73cc-a60e-11e4-97b6-680fdb087941.png)

**Comment by seanmcintyre** [comment]
@alisoniven Should I create one label for each section?  Or one label for each item?  I'm guessing the prior?

Email
[email]
[email]

Phone
[phone]

?

**Comment by seanmcintyre** [comment]
Phone numbers have labels, but email addresses do not.  We could add labels to email address if you think each individual item should have its own label.

**Comment by alisoniven** [comment]
A label for each section. Unless they've specified a "type" for the telephone when adding it. I don't think emails need one as they are mostly just "primary" and non-primary.
