### ISSUE TITLE
'Edit profile' modal edits

### ISSUE THREAD

**Issue by alisoniven** [sharewave/frontus#1519]
- [x] When I cleared my work address in the "edit profile" modal, it removed all input fields. It should just remove the information out of the input fields while keeping fields there (same for all input fields). "add address" also doesn't work from this state
![screen shot 2015-01-27 at 10 44 02 am](https://cloud.githubusercontent.com/assets/6333864/5921385/956ae0e0-a611-11e4-89ad-67b2d6a154bc.png)

- [x] email address should keep same styling on input field as other
- [x] remove ability to "clear" email address if user has logged in before. (we want to keep their email)
- [x] doesn't save 2nd telephone number, when entered.
- [x] adding a custom type doesn't display on user's profile. nor when you re-open modal
- [x] type dropdown doesn't have a hover state on options (should be grey background like others)
- [x] i only have one address on my profile, but when i click modal, there are two-input areas and my current address moved down one position.
![screen shot 2015-01-27 at 10 50 04 am](https://cloud.githubusercontent.com/assets/6333864/5921485/42bd6768-a612-11e4-9465-f04a01cc1125.png)
![screen shot 2015-01-27 at 10 44 02 am](https://cloud.githubusercontent.com/assets/6333864/5921486/45eb9c70-a612-11e4-9dd9-28c91709620e.png)

- [x]  without refreshing my browser but visiting and re-visiting page, system is adding multiple email addresses to profile
![screen shot 2015-01-27 at 10 50 33 am](https://cloud.githubusercontent.com/assets/6333864/5921503/657792e2-a612-11e4-83e9-df821bfa86ef.png)

- [x] current my profile experience for verifying email address should be replicated in new profile.
![screen shot 2015-01-27 at 11 00 52 am](https://cloud.githubusercontent.com/assets/6333864/5921714/dbc67cb4-a613-11e4-8914-087e8f028b79.png)

**Comment by seanmcintyre** [comment]
I know we want to start clumping issues together in single tickets, but I think this one may have swing the pendulum too far.

**Comment by alisoniven** [comment]
@seanmcintyre ok. sorry. i'll not put all together next time. i'm trying to sort best way still...

**Comment by seanmcintyre** [comment]
no worries
