### ISSUE TITLE
login button not responsive

### ISSUE THREAD

**Issue by jslevine** [sharewave/frontus#1533]
the login button in production does not move about with the window size, ie. it can get hidden. that's no good.

**Comment by seanmcintyre** [comment]
It looks like this was intentional to prevent users from logging in on phones and tablets.  Are you seeing in on a desktop with browser window size that's a little skinny?

**Comment by jslevine** [comment]
yes, it looks intentional and it's easy to make the button go away with window size. however, it's a bad user experience. i suggest making it responsive, make the login page responsive and then have the logged in home be either responsive or ambivalent.
