### ISSUE TITLE
User (my acct) is in a group but it's not checked in the dropdown. So no way to remove.

### ISSUE THREAD

**Issue by alisoniven** [sharewave/frontus#1534]
User (my acct) is in a group but it's not checked in the dropdown. So no way to remove.
![screen shot 2015-01-28 at 10 20 32 am](https://cloud.githubusercontent.com/assets/6333864/5940208/532de2ba-a6d7-11e4-8843-3bd7c0e24fb2.png)

**Comment by alisoniven** [comment]
added user to a group in the library. refreshed. went to user's profile and group is no longer checked (no errors in console)
![screen shot 2015-01-28 at 4 46 26 pm](https://cloud.githubusercontent.com/assets/6333864/5947697/3fcbfd7a-a70d-11e4-874f-ee1a5d2d71d1.png)

**Comment by BertHartm** [comment]
it feels a race condition on the profile page loading.
