### ISSUE TITLE
assigning two cap table rows to 1 contact w/ no email yet entered

### ISSUE THREAD

**Issue by alanmcgee** [sharewave/frontus#1566]
modal fail:
![screen shot 2015-01-30 at 10 29 20 am](https://cloud.githubusercontent.com/assets/2709177/5978061/e5dbaff4-a86a-11e4-99d5-e6f2e438ef05.png)

console msg:
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: u in users, Duplicate key: object:4849, Duplicate value: {"user_id":"232715107","name":"Investor 2","groups":[],"roles":["investor"],"emails":[],"last_login":null,"hasEmail":false,"hasAddress":false,"access":""}
http://errors.angularjs.org/1.3.5/ngRepeat/dupes?p0=u%20in%20users&p1=objec…2hasEmail%22%3Afalse%2C%22hasAddress%22%3Afalse%2C%22access%22%3A%22%22%7D

**Comment by BertHartm** [comment]
need to collapse duplicates in the list of people we're asking email
addresses for..
