### ISSUE TITLE
add contact modal spacing

### ISSUE THREAD

**Issue by alisoniven** [sharewave/frontus#1642]
![sharewave home](https://cloud.githubusercontent.com/assets/6333864/6028870/b0f8d656-abba-11e4-8907-f8da81c65ed4.png)

**Comment by seanmcintyre** [comment]
Should the email input be full length or should it mimic the edit profile modal?

**Comment by seanmcintyre** [comment]
Ditto for the spacing.  It's currently the same as the edit profile modal.  Should I change both?

**Comment by alisoniven** [comment]
yes plz. change on both.
