### ISSUE TITLE
if I add a new contact and do not enter an email, I shouldn't get the update email address modal immediately upon clicking the confirm button.

### ISSUE THREAD

**Issue by alisoniven** [sharewave/frontus#1644]
I think if I add a new contact and do not enter an email, I shouldn't get the update email address modal immediately upon clicking the confirm button. (user is silly, but i'm not actively sharing yet, so it's ok.)
![screen shot 2015-02-03 at 3 40 22 pm](https://cloud.githubusercontent.com/assets/6333864/6028926/134d2866-abbb-11e4-9765-f8e2dc7d5b48.png)

**Comment by seanmcintyre** [comment]
This should show up if you set a user role to something other than Contact, because an email is necessary for the other three roles.

**Comment by alisoniven** [comment]
that's fine for the other ones. but it does this for a reg contact as well.
