### ISSUE TITLE
clicking link in email as an admin ends in 404 page

### ISSUE THREAD

**Issue by alisoniven** [sharewave/frontus#1647]
got an email that i was added to a company as an admin and when i clicked on the link in the email went to a 404 page.
![screen shot 2015-02-03 at 4 05 36 pm](https://cloud.githubusercontent.com/assets/6333864/6029439/9aaf3fee-abbe-11e4-97a5-a6e3791f577e.png)
![screen shot 2015-02-03 at 4 05 47 pm](https://cloud.githubusercontent.com/assets/6333864/6029438/999edb14-abbe-11e4-8300-a30f6228a682.png)

**Comment by BertHartm** [comment]
problem on testing, closing as we're well aware of it and working on it.
