### ISSUE TITLE
Not receiving emails when I add a new person

### ISSUE THREAD

**Issue by alisoniven** [sharewave/frontus#355]
Created a new user, not admin. No email
Changed this new user to be an admin. No email notifying of status.
This user will receive a message email, I still can't log in.
![screen shot 2014-08-11 at 3 51 37 pm](https://cloud.githubusercontent.com/assets/6333864/3881795/ec520484-2190-11e4-97a9-41aa7f1bedb2.png)

However, if I add a new user and check the admin box before sending, that user becomes an admin and is notified via email.

**Comment by elizabethkilson** [comment]
Cannot reproduce, and relevant code has been worked on since the ticket was opened.
