### ISSUE TITLE
Date formatting is all different across site. Need to be consistent 

### ISSUE THREAD

**Issue by alisoniven** [sharewave/frontus#364]
I'm OK with activity feed dates being different from other transaction type dates on the site. I suggest that all dates be written out June 5, 2014 as it's easiest to read.

![edits-2014 08 12c](https://cloud.githubusercontent.com/assets/6333864/3893040/823236a8-2237-11e4-9a19-25fe0f835a5d.png)

**Comment by r0ml** [comment]
Consolidated into #1506
