### ISSUE TITLE
options: opt out of cap table transactions created on send if signature present

### ISSUE THREAD

**Issue by alanmcgee** [sharewave/frontus#720]
in combination with #719 we need to show the company that cap table transactions are created on send for every option grant (even with signatures requested), but give them the option to change this preference during setup.

**Comment by alisoniven** [comment]
Create 3rd tile on "review" step that just verifies that the issuer wants transaction to be created on the send. 

![edits-2015 02 02a](https://cloud.githubusercontent.com/assets/6333864/6006185/720693a2-aade-11e4-996b-9f07991a824e.png)

**Comment by BertHartm** [comment]
we probably need to work on the concept of "draft" transactions and running scenarios against the captable first, as
1) users will at some point want to transactions that have potential of being created. Certainly auditors would care.
2) it's much easier to create the transaction on send, and have it switch scenario / status than to create it on signing.

**Comment by alisoniven** [comment]
Yes, there is a concept of drafted transactions in: 2014.10-grants2.ai
![grants](https://cloud.githubusercontent.com/assets/6333864/6006661/27187be0-aae2-11e4-9fdb-6b9268a9f072.png)
![grants2](https://cloud.githubusercontent.com/assets/6333864/6006660/27186772-aae2-11e4-9d08-12610aeb52b8.png)

**Comment by BertHartm** [comment]
if we have this, do we need the checkbox, or is this as default behavior good enough?

I think to get the desired behavior, it's filtering on the captable view ("show pending" or similar in the filter rail) instead of a choice at document sending time.

**Comment by alisoniven** [comment]
def on the filter. that way the totals can get adjusted accordingly if viewing pending or not. 

according to initial ticket description, we need some way to allow them to not create the transaction on send. putting it here makes the most sense since user is in process and actively thinking about desired behavior or action..

**Comment by alanmcgee** [comment]
closed from discussion w/ bert and alison
